import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Files and nested folders supply the items; only section roots are configured here.
const sidebars: SidebarsConfig = {
  referenceSidebar: [{type: 'autogenerated', dirName: '.'}],
  howToSidebar: [
    {type: 'autogenerated', dirName: 'how-to'},
    {
      type: 'category',
      label: 'Tutorial basics',
      className: 'sidebar-shell-group',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial extras',
      className: 'sidebar-shell-group',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;
